# This file has been generated by the Python script /home/adematti/anaconda3/envs/cosmopipe/lib/python3.8/site-packages/pypescript/setuppype/generate_section_names.py
# Edit the root file section_names.yaml if necessary.
model = 'model'
data = 'data'
covariance = 'covariance'
likelihood = 'likelihood'
common = 'common'
parameters = 'parameters'
cosmological_parameters = 'cosmological_parameters'
background = 'background'
primordial_perturbations = 'primordial_perturbations'
primordial_cosmology = 'primordial_cosmology'
survey_geometry = 'survey_geometry'
galaxy_bias = 'galaxy_bias'
effect_ap = 'effect_ap'
galaxy_power = 'galaxy_power'
galaxy_rsd = 'galaxy_rsd'
mpi = 'mpi'
nocopy = ['mpi', 'common']